pipeline:
  build:
    image: telephoneorg/docker-builder
    environment:
    - KERNEL_VERSION=${KERNEL_VERSION}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - make build
    when:
      event: tag

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: dist/${KERNEL_VERSION}/*
    file_exists: overwrite
    checksum: sha256
    when:
      event: tag

matrix:
  KERNEL_VERSION:
  - 4.9.46
